version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  scraper:
    build: .
    environment:
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
